### ISSUE TITLE
Regex does not match methods with no arguments

### ISSUE THREAD

**Issue by zorkian** [perix4/vs-code-elixir-symbols#1]
Hiya,

The regex to match functions should probably use `.*?` instead of `.+?` in order to match functions with no arguments?

Also, I think technically you don't need the parenthesis if there are no arguments.

Thanks for doing this, though!

**Comment by perix4** [comment]
Thanks for the feedback, I fixed the issue and published 0.0.4 tag to Marketplace (https://marketplace.visualstudio.com/items?itemName=pkujundzic.elixir-symbols)
