### ISSUE TITLE
Go to symbol in workspace

### ISSUE THREAD

**Issue by the-shank** [perix4/vs-code-elixir-symbols#2]
Thank you for this extension ! The _"Go to Symbol in File..."_ works perfect for the current file. Is it possible to add the functionality for _"Go to Symbol in Workspace..."_. I could have helped but I dont know Typescript...

**Comment by the-shank** [comment]
@perix4 if possible please add the _"Go to Symbol in Workspace..."_ functionality..

**Comment by perix4** [comment]
No plans at the moment, in the meanwhile ElixirLS has implemented this feature so this extension is pretty unnecessary :)
