### ISSUE TITLE
Concerning Localio! You block issue but I have feedback

### ISSUE THREAD

**Issue by tatiesmars** [perix4/vs-code-elixir-symbols#3]
Hey Perix4! I just find your fork of localio and your work save me a lot of time! Thanks a lot for sharing that ❤️ 

I was wondering do you plan to keep working on it ? I wonder if you would like to support Domain-based translation? 

Keep up the good work!

**Comment by perix4** [comment]
Hi, sorry, for late reply, I have abandoned localio since Ruby isn't my main language, but if you want fork the repo and do the Domain-based translation.
